-- tutorial here: https://www.youtube.com/watch?v=vdn_pKJUda8
require("vcrini.plugins-setup")
require("vcrini.core.options")
require("vcrini.core.keymaps")
require("vcrini.core.colorscheme")
require("vcrini.plugins.comment")
require("vcrini.plugins.nvim-tree")
require("vcrini.plugins.lualine")
require("vcrini.plugins.telescope")
require("vcrini.plugins.nvim-cmp")
require("vcrini.plugins.lsp.mason")
require("vcrini.plugins.lsp.lspsaga")
require("vcrini.plugins.lsp.lspconfig")
require("vcrini.plugins.lsp.null-ls")
require("vcrini.plugins.autopairs")
require("vcrini.plugins.treesitter")
require("vcrini.plugins.gitsigns")
require("vcrini.plugins.trouble")
